
@baseUrl = http://localhost:3000

@jwtToken = {{authlogin.response.body.acessToken}}

### Auth login
# @name authlogin
POST  {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email":"Mateus@email.com",
  "password":"12345"

}

### Create user
# @name CreateUser
POST  {{baseUrl}}/user
Content-Type: application/json

{
  "name":"Mateus",
  "email":"Mateus@email.com",
  "password":"12345"

}

### Uptade User
# @name UptadeUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
"name":"Mateus",
"email":"Mateu1s@emai.com"
}


### Read one user //ler um úsuario
# @name readOneUser
GET  {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}


